services:
  app0:
    build: ./app
    image: app-backend
    ports:
      - 8080:3000
    volumes:
      - ./app/src:/usr/src/ap/src
    environment:
      - POD_NUMBER=0
      - MONGO_URL=mongodb://root:example@mongo:27017

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example