services:
  app0:
    build: ./app
    environment:
      - POD_NUMBER=0
  
  app1:
    build: ./app
    environment:
      - POD_NUMBER=1

  app2:
    build: ./app
    environment:
      - POD_NUMBER=2
  
  web:
    image: nginx
    volumes:
    - ./load-balance:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
    - app0
    - app1
    - app2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  client:
    build: ./client
    depends_on:
      web:
        condition: service_healthy