services:
  app0:
    build: ./app
    image: app-backend
    volumes:
      - ./app/src:/usr/src/app/src
    environment:
      - POD_NUMBER=0
      - MONGO_URL=mongodb://root:example@mongo:27017
      - REDIS_URL=redis://cache:6379
      - PUBLIC_LIMIT=20000
  
  app1:
    image: app-backend
    volumes:
      - ./app/src:/usr/src/app/src
    depends_on:
      - app0
    environment:
      - POD_NUMBER=1
      - MONGO_URL=mongodb://root:example@mongo:27017
      - REDIS_URL=redis://cache:6379
      - PUBLIC_LIMIT=20000

  app2:
    image: app-backend
    volumes:
      - ./app/src:/usr/src/app/src
    depends_on:
      - app0
    environment:
      - POD_NUMBER=2
      - MONGO_URL=mongodb://root:example@mongo:27017
      - REDIS_URL=redis://cache:6379
      - PUBLIC_LIMIT=20000
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes: 
      - ./cache:/data
  
  web:
    image: nginx
    volumes:
    - ./load-balance:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
    - app0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    logging:
      driver: none
  
  # client:
  #   build: ./client
  #   depends_on:
  #     web:
  #       condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      driver: none